# Generated by Django 3.1.14 on 2022-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=128, verbose_name='English')),
                ('uzbek', models.CharField(max_length=128, verbose_name='Uzbek')),
            ],
        ),
    ]
